name: deploy on google play

on:
  push:
    branches: [ "master" ]


jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run microTest
      run: ./gradlew testDebug

  distrbuite:
    name: Distribute Bundle to google play
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
            gradlePath: app/build.gradle.kts
            versionCode: ${{ github.run_number }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease


      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
            releaseDirectory: app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
            keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
            alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
            keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}

      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
              serviceAccountJson: service_account.json
              packageName: com.beshoy.friends
              releaseFiles: app/build/outputs/bundle/release/app-release.aab
              track: 'internal'
              status: 'completed'
              whatsNewDirectory: whatsNew/